[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "ni-d1"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
datalad = ">=1.4.1, <2"
datalad-next = ">=1.6.0, <2"
git-annex = ">=10.20250721, <11"
datalad-osf = ">=0.3.0, <0.4"
pandas = ">=3.0.3, <4"
seaborn = ">=0.13.2, <0.14"
